Repository Real-Dev-Squad/website-my, pull requests merged in 2021-02, with the labels that each got.

#30 Allows empty website to be sent in the form
  app/controllers/signup.js
Labels: bug-fix

#35 Adds the API URL to environment variable
  app/controllers/signup.js
  config/environment.js
Labels: refactor

#37 Added npm package updates and port change in dev to 80
  package-lock.json
  package.json
Labels: feature-task

#38 Disable the form for those who have already filled the form
  app/routes/signup.js
Labels: enhancement

#44 Added new field Instagram ID
  app/controllers/signup.js
Labels: enhancement
