Repository Real-Dev-Squad/website-my, pull requests merged in 2023-05, with the labels that each got.

#381 Added /mobile route to show the QR
  app/components/qrcode.hbs
  app/controllers/mobile.js
  app/router.js
  app/routes/mobile.js
  app/styles/app.css
  app/styles/qrcode.css
  app/templates/index.hbs
  app/templates/mobile.hbs
  package.json
  tests/integration/components/qrcode-test.js
  tests/unit/routes/mobile-test.js
  yarn.lock
Labels: enhancement, feature task

#394 added ONBOARDING userstate to render userStatus UI
  app/components/user-status.hbs
  app/components/user-status.js
  app/constants/user-status.js
  app/styles/user-status.css
  app/styles/variables.css
Labels: bug, bugfix, dependencies

#391 Redesign profile page
  app/components/profile-field.hbs
  app/components/profile-field.js
  app/controllers/profile.js
  app/styles/profile.css
  app/styles/variables.css
  app/templates/profile.hbs
  public/icons/company.svg
  public/icons/cross.svg
  public/icons/linkedin.svg
  public/icons/mail.svg
  public/icons/twitter.svg
  public/icons/user.svg
  public/icons/website.svg
  tests/integration/components/profile-field-test.js
Labels: feature task

#407 Redesign the discord linking page
  app/styles/discord.css
  app/templates/discord.hbs
  public/DiscordConnector.svg
  public/DiscordLogo.png
Labels: UX, UI

#410 write tests for the discord link page
  app/templates/discord.hbs
  tests/acceptance/discord-test.js
Labels: tests
